### ISSUE TITLE
再debian 9上编译失败

### ISSUE THREAD

**Issue by whonchen** [shadowsocksr/shadowsocksr-libev#23]
编译版本：shadowsocksr-libev-2.4.1
操作系统：debian 9 stretch
                  执行 ./autogen.sh   和   ./configure 成功
                  make失败：

make  all-recursive
make[1]: Entering directory '/home/wang/桌面/shadowsocksr-libev-2.4.1'
Making all in libsodium
make[2]: Entering directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/libsodium'
Making all in src
make[3]: Entering directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/libsodium/src'
Making all in libsodium
make[4]: Entering directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/libsodium/src/libsodium'
Making all in include
make[5]: Entering directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/libsodium/src/libsodium/include'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/libsodium/src/libsodium/include'
make[5]: Entering directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/libsodium/src/libsodium'
  CC       crypto_aead/chacha20poly1305/sodium/libsodium_la-aead_chacha20poly1305.lo
  CC       crypto_auth/libsodium_la-crypto_auth.lo
  CC       crypto_auth/hmacsha256/libsodium_la-auth_hmacsha256_api.lo
  CC       crypto_auth/hmacsha256/cp/libsodium_la-hmac_hmacsha256.lo
  CC       crypto_auth/hmacsha256/cp/libsodium_la-verify_hmacsha256.lo
  CC       crypto_auth/hmacsha512/libsodium_la-auth_hmacsha512_api.lo
  CC       crypto_auth/hmacsha512/cp/libsodium_la-hmac_hmacsha512.lo
  CC       crypto_auth/hmacsha512/cp/libsodium_la-verify_hmacsha512.lo
  CC       crypto_auth/hmacsha512256/libsodium_la-auth_hmacsha512256_api.lo
  CC       crypto_auth/hmacsha512256/cp/libsodium_la-hmac_hmacsha512256.lo
  CC       crypto_auth/hmacsha512256/cp/libsodium_la-verify_hmacsha512256.lo
  CC       crypto_box/libsodium_la-crypto_box.lo
  CC       crypto_box/libsodium_la-crypto_box_easy.lo
  CC       crypto_box/libsodium_la-crypto_box_seal.lo
  CC       crypto_box/curve25519xsalsa20poly1305/libsodium_la-box_curve25519xsalsa20poly1305_api.lo
  CC       crypto_box/curve25519xsalsa20poly1305/ref/libsodium_la-after_curve25519xsalsa20poly1305.lo
  CC       crypto_box/curve25519xsalsa20poly1305/ref/libsodium_la-before_curve25519xsalsa20poly1305.lo
  CC       crypto_box/curve25519xsalsa20poly1305/ref/libsodium_la-box_curve25519xsalsa20poly1305.lo
  CC       crypto_box/curve25519xsalsa20poly1305/ref/libsodium_la-keypair_curve25519xsalsa20poly1305.lo
  CC       crypto_core/hsalsa20/ref2/libsodium_la-core_hsalsa20.lo
  CC       crypto_core/hsalsa20/libsodium_la-core_hsalsa20_api.lo
  CC       crypto_core/salsa20/ref/libsodium_la-core_salsa20.lo
  CC       crypto_core/salsa20/libsodium_la-core_salsa20_api.lo
  CC       crypto_generichash/libsodium_la-crypto_generichash.lo
  CC       crypto_generichash/blake2/libsodium_la-generichash_blake2_api.lo
  CC       crypto_generichash/blake2/ref/libsodium_la-blake2b-compress-ref.lo
  CC       crypto_generichash/blake2/ref/libsodium_la-blake2b-ref.lo
  CC       crypto_generichash/blake2/ref/libsodium_la-generichash_blake2b.lo
  CC       crypto_hash/libsodium_la-crypto_hash.lo
  CC       crypto_hash/sha256/libsodium_la-hash_sha256_api.lo
  CC       crypto_hash/sha256/cp/libsodium_la-hash_sha256.lo
  CC       crypto_hash/sha512/libsodium_la-hash_sha512_api.lo
  CC       crypto_hash/sha512/cp/libsodium_la-hash_sha512.lo
  CC       crypto_onetimeauth/libsodium_la-crypto_onetimeauth.lo
  CC       crypto_onetimeauth/poly1305/libsodium_la-onetimeauth_poly1305.lo
  CC       crypto_onetimeauth/poly1305/donna/libsodium_la-poly1305_donna.lo
  CC       crypto_pwhash/scryptsalsa208sha256/libsodium_la-crypto_scrypt-common.lo
  CC       crypto_pwhash/scryptsalsa208sha256/libsodium_la-scrypt_platform.lo
  CC       crypto_pwhash/scryptsalsa208sha256/libsodium_la-pbkdf2-sha256.lo
  CC       crypto_pwhash/scryptsalsa208sha256/libsodium_la-pwhash_scryptsalsa208sha256.lo
  CC       crypto_pwhash/scryptsalsa208sha256/nosse/libsodium_la-pwhash_scryptsalsa208sha256_nosse.lo
  CC       crypto_scalarmult/libsodium_la-crypto_scalarmult.lo
  CC       crypto_scalarmult/curve25519/libsodium_la-scalarmult_curve25519.lo
  CC       crypto_secretbox/libsodium_la-crypto_secretbox.lo
  CC       crypto_secretbox/libsodium_la-crypto_secretbox_easy.lo
  CC       crypto_secretbox/xsalsa20poly1305/libsodium_la-secretbox_xsalsa20poly1305_api.lo
  CC       crypto_secretbox/xsalsa20poly1305/ref/libsodium_la-box_xsalsa20poly1305.lo
  CC       crypto_shorthash/libsodium_la-crypto_shorthash.lo
  CC       crypto_shorthash/siphash24/libsodium_la-shorthash_siphash24_api.lo
  CC       crypto_shorthash/siphash24/ref/libsodium_la-shorthash_siphash24.lo
  CC       crypto_sign/libsodium_la-crypto_sign.lo
  CC       crypto_sign/ed25519/libsodium_la-sign_ed25519_api.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-fe_0.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-fe_1.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-fe_add.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-fe_cmov.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-fe_copy.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-fe_frombytes.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-fe_invert.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-fe_isnegative.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-fe_isnonzero.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-fe_mul.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-fe_neg.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-fe_pow22523.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-fe_sq.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-fe_sq2.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-fe_sub.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-fe_tobytes.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-ge_add.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-ge_double_scalarmult.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-ge_frombytes.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-ge_madd.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-ge_msub.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-ge_p1p1_to_p2.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-ge_p1p1_to_p3.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-ge_p2_0.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-ge_p2_dbl.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-ge_p3_0.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-ge_p3_dbl.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-ge_p3_to_cached.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-ge_p3_to_p2.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-ge_p3_tobytes.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-ge_precomp_0.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-ge_scalarmult_base.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-ge_sub.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-ge_tobytes.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-keypair.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-open.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-sc_muladd.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-sc_reduce.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-sign.lo
  CC       crypto_stream/libsodium_la-crypto_stream.lo
  CC       crypto_stream/chacha20/libsodium_la-stream_chacha20.lo
  CC       crypto_stream/chacha20/ref/libsodium_la-stream_chacha20_ref.lo
  CC       crypto_stream/salsa20/libsodium_la-stream_salsa20_api.lo
  CC       crypto_stream/xsalsa20/libsodium_la-stream_xsalsa20_api.lo
  CC       crypto_stream/xsalsa20/ref/libsodium_la-stream_xsalsa20.lo
  CC       crypto_stream/xsalsa20/ref/libsodium_la-xor_xsalsa20.lo
  CC       crypto_verify/16/libsodium_la-verify_16_api.lo
  CC       crypto_verify/16/ref/libsodium_la-verify_16.lo
  CC       crypto_verify/32/libsodium_la-verify_32_api.lo
  CC       crypto_verify/32/ref/libsodium_la-verify_32.lo
  CC       crypto_verify/64/libsodium_la-verify_64_api.lo
  CC       crypto_verify/64/ref/libsodium_la-verify_64.lo
  CC       randombytes/libsodium_la-randombytes.lo
  CC       sodium/libsodium_la-core.lo
  CC       sodium/libsodium_la-runtime.lo
  CC       sodium/libsodium_la-utils.lo
  CC       sodium/libsodium_la-version.lo
  CC       randombytes/salsa20/libsodium_la-randombytes_salsa20_random.lo
  CC       randombytes/sysrandom/libsodium_la-randombytes_sysrandom.lo
  CC       crypto_scalarmult/curve25519/donna_c64/libsodium_la-curve25519_donna_c64.lo
  CC       crypto_scalarmult/curve25519/sandy2x/libsodium_la-curve25519_sandy2x.lo
  CC       crypto_scalarmult/curve25519/sandy2x/libsodium_la-fe51_invert.lo
  CC       crypto_scalarmult/curve25519/sandy2x/libsodium_la-fe_frombytes_sandy2x.lo
  CPPAS    crypto_scalarmult/curve25519/sandy2x/libsodium_la-sandy2x.lo
  CPPAS    crypto_stream/salsa20/amd64_xmm6/libsodium_la-stream_salsa20_amd64_xmm6.lo
  CC       crypto_core/salsa2012/ref/libsodium_la-core_salsa2012.lo
  CC       crypto_core/salsa2012/libsodium_la-core_salsa2012_api.lo
  CC       crypto_core/salsa208/ref/libsodium_la-core_salsa208.lo
  CC       crypto_core/salsa208/libsodium_la-core_salsa208_api.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-obsolete.lo
  CC       crypto_stream/aes128ctr/portable/libsodium_la-afternm_aes128ctr.lo
  CC       crypto_stream/aes128ctr/libsodium_la-stream_aes128ctr_api.lo
  CC       crypto_stream/aes128ctr/portable/libsodium_la-beforenm_aes128ctr.lo
  CC       crypto_stream/aes128ctr/portable/libsodium_la-common_aes128ctr.lo
  CC       crypto_stream/aes128ctr/portable/libsodium_la-consts_aes128ctr.lo
  CC       crypto_stream/aes128ctr/portable/libsodium_la-int128_aes128ctr.lo
  CC       crypto_stream/aes128ctr/portable/libsodium_la-stream_aes128ctr.lo
  CC       crypto_stream/aes128ctr/portable/libsodium_la-xor_afternm_aes128ctr.lo
  CC       crypto_stream/salsa2012/libsodium_la-stream_salsa2012_api.lo
  CC       crypto_stream/salsa2012/ref/libsodium_la-stream_salsa2012.lo
  CC       crypto_stream/salsa2012/ref/libsodium_la-xor_salsa2012.lo
  CC       crypto_stream/salsa208/libsodium_la-stream_salsa208_api.lo
  CC       crypto_stream/salsa208/ref/libsodium_la-stream_salsa208.lo
  CC       crypto_stream/salsa208/ref/libsodium_la-xor_salsa208.lo
  CC       crypto_aead/aes256gcm/aesni/libaesni_la-aead_aes256gcm_aesni.lo
  CCLD     libaesni.la
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       crypto_pwhash/scryptsalsa208sha256/sse/libsse2_la-pwhash_scryptsalsa208sha256_sse.lo
  CC       crypto_onetimeauth/poly1305/sse2/libsse2_la-poly1305_sse2.lo
  CCLD     libsse2.la
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       crypto_generichash/blake2/ref/libssse3_la-blake2b-compress-ssse3.lo
  CC       crypto_stream/chacha20/vec/libssse3_la-stream_chacha20_vec.lo
  CCLD     libssse3.la
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       crypto_generichash/blake2/ref/libsse41_la-blake2b-compress-sse41.lo
  CCLD     libsse41.la
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
ar: `u' modifier ignored since `D' is the default (see `U')
  CCLD     libsodium.la
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
ar: `u' modifier ignored since `D' is the default (see `U')
make[5]: Leaving directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/libsodium/src/libsodium'
make[4]: Leaving directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/libsodium/src/libsodium'
make[4]: Entering directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/libsodium/src'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/libsodium/src'
make[3]: Leaving directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/libsodium/src'
make[3]: Entering directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/libsodium'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/libsodium'
make[2]: Leaving directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/libsodium'
Making all in libcork
make[2]: Entering directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/libcork'
  CC       cli/libcork_la-commands.lo
  CC       core/libcork_la-allocator.lo
  CC       core/libcork_la-error.lo
  CC       core/libcork_la-gc.lo
  CC       core/libcork_la-hash.lo
  CC       core/libcork_la-ip-address.lo
  CC       core/libcork_la-mempool.lo
  CC       core/libcork_la-timestamp.lo
  CC       core/libcork_la-u128.lo
  CC       ds/libcork_la-array.lo
  CC       ds/libcork_la-bitset.lo
  CC       ds/libcork_la-buffer.lo
  CC       ds/libcork_la-dllist.lo
  CC       ds/libcork_la-file-stream.lo
  CC       ds/libcork_la-hash-table.lo
  CC       ds/libcork_la-managed-buffer.lo
  CC       ds/libcork_la-ring-buffer.lo
  CC       ds/libcork_la-slice.lo
  CC       posix/libcork_la-directory-walker.lo
  CC       posix/libcork_la-env.lo
  CC       posix/libcork_la-exec.lo
  CC       posix/libcork_la-files.lo
  CC       posix/libcork_la-process.lo
  CC       posix/libcork_la-subprocess.lo
  CC       pthreads/libcork_la-thread.lo
  CCLD     libcork.la
ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/libcork'
Making all in libipset
make[2]: Entering directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/libipset'
  CC       libipset_la-general.lo
  CC       bdd/libipset_la-assignments.lo
  CC       bdd/libipset_la-basics.lo
  CC       bdd/libipset_la-bdd-iterator.lo
  CC       bdd/libipset_la-expanded.lo
  CC       bdd/libipset_la-reachable.lo
  CC       bdd/libipset_la-read.lo
  CC       bdd/libipset_la-write.lo
  CC       map/libipset_la-allocation.lo
  CC       map/libipset_la-inspection.lo
  CC       map/libipset_la-ipv4_map.lo
  CC       map/libipset_la-ipv6_map.lo
  CC       map/libipset_la-storage.lo
  CC       set/libipset_la-allocation.lo
  CC       set/libipset_la-inspection.lo
  CC       set/libipset_la-ipv4_set.lo
  CC       set/libipset_la-ipv6_set.lo
  CC       set/libipset_la-iterator.lo
  CC       set/libipset_la-storage.lo
  CCLD     libipset.la
copying selected object files to avoid basename conflicts...
ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/libipset'
Making all in libudns
make[2]: Entering directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/libudns'
  CC       udns_dn.lo
  CC       udns_dntosp.lo
  CC       udns_parse.lo
  CC       udns_resolver.lo
  CC       udns_init.lo
  CC       udns_misc.lo
  CC       udns_XtoX.lo
  CC       udns_rr_a.lo
  CC       udns_rr_ptr.lo
  CC       udns_rr_mx.lo
  CC       udns_rr_txt.lo
  CC       udns_bl.lo
  CC       udns_rr_srv.lo
  CC       udns_rr_naptr.lo
  CC       udns_codes.lo
  CC       udns_jran.lo
  CCLD     libudns.la
ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/libudns'
Making all in libev
make[2]: Entering directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/libev'
  CC       ev.lo
ev.c:1692:31: warning: ‘ev_default_loop_ptr’ initialized and declared ‘extern’
   EV_API_DECL struct ev_loop *ev_default_loop_ptr = 0; /* needs to be initialised to make it a definition despite extern */
                               ^~~~~~~~~~~~~~~~~~~
  CC       event.lo
  CCLD     libev.la
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
ar: `u' modifier ignored since `D' is the default (see `U')
make[2]: Leaving directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/libev'
Making all in src
make[2]: Entering directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/src'
  CC       libshadowsocks_libev_la-utils.lo
  CC       libshadowsocks_libev_la-jconf.lo
  CC       libshadowsocks_libev_la-json.lo
  CC       libshadowsocks_libev_la-encrypt.lo
In file included from encrypt.c:77:0:
encrypt.h:108:18: error: field ‘evp’ has incomplete type
     cipher_evp_t evp;
                  ^~~
encrypt.c: In function ‘enc_key_init’:
encrypt.c:1486:17: error: storage size of ‘cipher_info’ isn’t known
     cipher_kt_t cipher_info;
                 ^~~~~~~~~~~
encrypt.c:1495:15: error: dereferencing pointer to incomplete type ‘cipher_kt_t {aka struct evp_cipher_st}’
         cipher->key_len = supported_ciphers_key_size[method];
               ^~
encrypt.c:1486:17: error: unused variable ‘cipher_info’ [-Werror=unused-variable]
     cipher_kt_t cipher_info;
                 ^~~~~~~~~~~
cc1: all warnings being treated as errors
Makefile:796: recipe for target 'libshadowsocks_libev_la-encrypt.lo' failed
make[2]: *** [libshadowsocks_libev_la-encrypt.lo] Error 1
make[2]: Leaving directory '/home/wang/桌面/shadowsocksr-libev-2.4.1/src'
Makefile:475: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/wang/桌面/shadowsocksr-libev-2.4.1'
Makefile:384: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Galaxy0419** [comment]
apt-get purge libsodium-dev
git clone https://github.com/jedisct1/libsodium
cd libsodium
./autogen.sh
./configure
sudo make install
ldconfig
