### ISSUE TITLE
Cannot establish available connection between c/s with ss-server on Debian 8

### ISSUE THREAD

**Issue by edgevent** [shadowsocksr/shadowsocksr-libev#24]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocksr-libev are you using?
latest

### What operating system are you using?
Debian 8.0 Jessie x86_64

### What did you do?
I've successfully compiled and installed shadowsocksr-libev from source, however when i tried to use ss-server to launch a proxy server there is still a error exists, which made connection reachable but unavailable for use :
root@jessie:~# /usr/local/shadowsocksr-libev/bin/ss-server -c /etc/config.json
2017-03-04 05:52:22 INFO: initializing ciphers... aes-192-cfb
2017-03-04 05:52:22 INFO: tcp port reuse enabled
2017-03-04 05:52:22 INFO: listening at 0.0.0.0:80
2017-03-04 05:52:22 INFO: running from root user
2017-03-04 05:52:46 ERROR: failed to handshake with 192.30.253.112
2017-03-04 05:52:49 ERROR: failed to handshake with 192.30.253.112
2017-03-04 05:52:52 ERROR: failed to handshake with 192.30.253.112
2017-03-04 05:53:16 ERROR: failed to handshake with 192.30.253.112

### What did you expect to see?
Just make shadowsocksr-libev works as well as python port of shadowsocksr.

### What is your config in detail (with all sensitive info masked)?
{ 
"server":"0.0.0.0",
"server_port":80,
"local_address":"0.0.0.0",
"local_port":1080,
"password":"passwd", 
"timeout":300,
"method":"aes-192-cfb", 
"protocol":"auth_aes128_sha1", 
"protocol_param": "",
"obfs":"http_post", 
"obfsparam":"" ,
"redirect":"bing.com"
}

**Comment by breakwa11** [comment]
ssr-libev is a client, can not run as a server

**Comment by edgevent** [comment]
fine, i see it.
btw, why do not work on server purpose like on client's ? aka the inplementation in C will serve it with extra performance better than other port .

**Comment by breakwa11** [comment]
I've no time to do that
