### ISSUE TITLE
请问如何bypass局域网和中国ip

### ISSUE THREAD

**Issue by jaoyina** [shadowsocksr/shadowsocksr-libev#29]
windows版可以选过滤规则，想问下linux上怎么搞？

**Comment by qinyuhang** [comment]
—acl <aclfile.acl>

**Comment by jaoyina** [comment]
@qinyuhang 那这个文件怎么生成呢，我还要手动ip地址放进去吗？

**Comment by qinyuhang** [comment]
see https://github.com/shadowsocksr/shadowsocksr-libev/tree/master/acl . You can download any of it and using it
