### ISSUE TITLE
设置内网共享不稳定问题

### ISSUE THREAD

**Issue by jaoyina** [shadowsocksr/shadowsocksr-libev#30]
我现在是这么配置的
{ 
"server":"xx.xx.xx.xx",
"server_port":8188,
"local_port":1080,
"password":"xxxx", 
"timeout":600,
"method":"aes-256-cfb", 
"protocol":"origin", 
"obfs":"tls1.2_ticket_auth", 
"obfsparam":"" ,
"remarks_base64":"QldH",
"group":"sfantree",
"local_address":"0.0.0.0",
}

现在情况是每次刚启动后可以在家里其他电脑通过wifi设置代理连到这台机器的1080端口可以访问，但是非常不稳定，时快时慢，同样我在windows版下用却要稳定很多，请教下是我的配置不太对还是说通过代理访问本来就是这样？

**Comment by breakwa11** [comment]
你确定你PC上用的也是origin协议？

**Comment by jaoyina** [comment]
是的，我这个也是从网上看来的，不清楚这个协议有啥区别，我昨天又试了下PC端，发现走代理我ps4没连上，上次试是还挺快的，我如果要局域网共享，应该用啥协议呢？

**Comment by jaoyina** [comment]
@breakwa11  刚才在windows下试了下，这个如果不是这origin，我本机都连不上网了，更不要说共享给局域网其他机器了，这个参数是和server端有什么配置要对应起来吗？

**Comment by breakwa11** [comment]
@jaoyina 。。。。。当然要和服务端协议要一样

**Comment by jaoyina** [comment]
@breakwa11 我刚才查了服务端，用的也是origina，不过我忘记当初这个配置从哪里拷贝过来的了，是不是换成auth_sha1_v4会稳定点？

**Comment by breakwa11** [comment]
用auth_sha1_v4或auth_aes128_md5测测

**Comment by jaoyina** [comment]
@breakwa11 我用的服务端个人版，就是进shadowsocksr/shadowsocks里的，然后运行命令python server.py -d start启动的，如何制定协议呢？我是在shadowsockr里改了下user-config.json但是好像没效果，我客户端还是必须选origin才可以连上。个人办的配置文件应该改那个，shadowsocks目录里没找到有config文件。

**Comment by jaoyina** [comment]
问下服务器端如何可以查看日志？

**Comment by jaoyina** [comment]
@breakwa11 改了auth_sha1_v4在windows客户端下没问题，但是树莓派下报错
Load obfs 'auth_sha1_v4' failed
这是为什么呢？

**Comment by breakwa11** [comment]
你用的版本有问题

**Comment by jaoyina** [comment]
@breakwa11 树莓派应该用哪个版本？我好像是直接便宜source出来的。

**Comment by breakwa11** [comment]
最新版本来编译
