### ISSUE TITLE
Kali(Debian)下编译失败

### ISSUE THREAD

**Issue by usualwyy** [shadowsocksr/shadowsocksr-libev#34]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
7daffe8

### What operating system are you using?
Linux kali-pentest 4.9.0-kali3-amd64 #1 SMP Debian 4.9.16-1kali1 (2017-03-24) x86_64 GNU/Linux

### What did you do?
./configure && make

### What did you expect to see?
顺利编译

### What did you see instead?
local.c: In function 'start_ss_local_server':
local.c:1971:15: error: 'cipher_env' undeclared (first use in this function)
     enc_init(&cipher_env, password, method);
               ^~~~~~~~~~
local.c:1971:15: note: each undeclared identifier is reported only once for each function it appears in
local.c:1984:15: error: 'listen_ctx_t {aka struct listen_ctx}' has no member named 'remote_num'; did you mean 'server_num'?
     listen_ctx.remote_num     = 1;
               ^
local.c:1985:15: error: 'listen_ctx_t {aka struct listen_ctx}' has no member named 'remote_addr'
     listen_ctx.remote_addr    = remote_addr_tmp;
               ^
local.c:1986:15: error: 'listen_ctx_t {aka struct listen_ctx}' has no member named 'remote_addr'
     listen_ctx.remote_addr[0] = (struct sockaddr *)storage;
               ^
local.c:2016:9: error: too few arguments to function 'init_udprelay'
         init_udprelay(local_addr, local_port_str, addr,
         ^~~~~~~~~~~~~
In file included from local.h:34:0,
                 from local.c:69:
common.h:35:5: note: declared here
 int init_udprelay(const char *server_host, const char *server_port,
     ^~~~~~~~~~~~~
In file included from ../libcork/include/libcork/ds.h:19:0,
                 from local.h:27,
                 from local.c:69:
local.c:2026:23: error: 'connections' undeclared (first use in this function)
     cork_dllist_init(&connections);
                       ^
../libcork/include/libcork/ds/dllist.h:34:10: note: in definition of macro 'cork_dllist_init'
         (list)->head.next = &(list)->head; \
          ^~~~
In file included from local.c:64:0:
local.c:2046:23: error: 'listen_ctx_t {aka struct listen_ctx}' has no member named 'remote_addr'
     ss_free(listen_ctx.remote_addr[0]);
                       ^
utils.h:229:14: note: in definition of macro 'ss_free'
         free(ptr);       \
              ^~~
local.c:2046:23: error: 'listen_ctx_t {aka struct listen_ctx}' has no member named 'remote_addr'
     ss_free(listen_ctx.remote_addr[0]);
                       ^
utils.h:230:9: note: in definition of macro 'ss_free'
         ptr = NULL;      \
         ^~~
At top level:
local.c:1394:1: error: 'init_obfs' defined but not used [-Werror=unused-function]
 init_obfs(server_def_t *serv, char *protocol, char *protocol_param, char *obfs, char *obfs_param)
 ^~~~~~~~~
local.c:139:27: error: 'inactive_profiles' defined but not used [-Werror=unused-variable]
 static struct cork_dllist inactive_profiles;
                           ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Makefile:854: recipe for target 'libshadowsocks_libev_la-local.lo' failed
make[2]: *** [libshadowsocks_libev_la-local.lo] Error 1
make[2]: Leaving directory '/root/shadowsocksr-libev/src'
Makefile:469: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/shadowsocksr-libev'
Makefile:377: recipe for target 'all' failed
make: *** [all] Error 2

### What is your config in detail (with all sensitive info masked)?
所有文档中提到的前置需求都安装过了，然后直接git clone，没有修改任何设置

**Comment by Portan** [comment]
我的是一样的错误，之前的版本没有任何问题。

**Comment by breakwa11** [comment]
最近两天在大改，先用3月25日这个版本 2670ab26ddd63dd790ba6c35f57d4dd040dec194 来编译吧

**Comment by breakwa11** [comment]
fixed
