### ISSUE TITLE
openwrt 3月27号更新过后的代码编译失败

### ISSUE THREAD

**Issue by chobitsos** [shadowsocksr/shadowsocksr-libev#38]
CC       ss_tunnel-utils.o
  CC       ss_tunnel-jconf.o
  CC       ss_tunnel-json.o
  CC       ss_tunnel-encrypt.o
  CC       ss_tunnel-udprelay.o
  CC       ss_tunnel-cache.o
  CC       ss_tunnel-netutils.o
  CC       ss_tunnel-tunnel.o
tunnel.c: In function 'server_recv_cb':
tunnel.c:212:27: error: 'cipher_env' undeclared (first use in this function)
     int err = ss_encrypt(&cipher_env, remote->buf, server->e_ctx, BUF_SIZE);
                           ^
tunnel.c:212:27: note: each undeclared identifier is reported only once for each function it appears in
tunnel.c: In function 'remote_recv_cb':
tunnel.c:394:27: error: 'cipher_env' undeclared (first use in this function)
     int err = ss_decrypt(&cipher_env, server->buf, server->d_ctx, BUF_SIZE);
                           ^
tunnel.c: In function 'remote_send_cb':
tunnel.c:531:35: error: 'cipher_env' undeclared (first use in this function)
             int err = ss_encrypt(&cipher_env, remote->buf, server->e_ctx, BUF_SIZE);
                                   ^
tunnel.c: In function 'new_server':
tunnel.c:680:23: error: 'cipher_env' undeclared (first use in this function)
         enc_ctx_init(&cipher_env, server->e_ctx, 1);
                       ^
tunnel.c: In function 'free_server':
tunnel.c:701:30: error: 'cipher_env' undeclared (first use in this function)
             enc_ctx_release(&cipher_env, server->e_ctx);
                              ^
tunnel.c: In function 'main':
tunnel.c:1005:30: error: 'jconf_t' has no member named 'remote_num'
             remote_num = conf->remote_num;
                              ^
tunnel.c:1007:38: error: 'jconf_t' has no member named 'remote_addr'
                 remote_addr[i] = conf->remote_addr[i];
                                      ^
tunnel.c:1010:31: error: 'jconf_t' has no member named 'remote_port'
             remote_port = conf->remote_port;
                               ^
tunnel.c:1013:30: error: 'jconf_t' has no member named 'local_addr'
             local_addr = conf->local_addr;
                              ^
tunnel.c:1016:30: error: 'jconf_t' has no member named 'local_port'
             local_port = conf->local_port;
                              ^
tunnel.c:1019:28: error: 'jconf_t' has no member named 'password'
             password = conf->password;
                            ^
tunnel.c:1023:28: error: 'jconf_t' has no member named 'protocol'
             protocol = conf->protocol;
                            ^
tunnel.c:1027:34: error: 'jconf_t' has no member named 'protocol_param'
             protocol_param = conf->protocol_param;
                                  ^
tunnel.c:1031:26: error: 'jconf_t' has no member named 'method'
             method = conf->method;
                          ^
tunnel.c:1035:24: error: 'jconf_t' has no member named 'obfs'
             obfs = conf->obfs;
                        ^
tunnel.c:1039:30: error: 'jconf_t' has no member named 'obfs_param'
             obfs_param = conf->obfs_param;
                              ^
tunnel.c:1131:23: error: 'cipher_env' undeclared (first use in this function)
     int m = enc_init(&cipher_env, password, method);
                       ^
tunnel.c:1191:23: error: passing argument 9 of 'init_udprelay' from incompatible pointer type [-Werror]
                       tunnel_addr, mtu, listen_ctx.timeout, iface, protocol, protocol_param);
                       ^
In file included from tunnel.h:31:0,
                 from tunnel.c:60:
common.h:40:5: note: expected 'struct cipher_env_t *' but argument is of type 'char *'
 int init_udprelay(const char *server_host, const char *server_port,
     ^
tunnel.c:1191:23: error: too few arguments to function 'init_udprelay'
                       tunnel_addr, mtu, listen_ctx.timeout, iface, protocol, protocol_param);
                       ^
In file included from tunnel.h:31:0,
                 from tunnel.c:60:
common.h:40:5: note: declared here
 int init_udprelay(const char *server_host, const char *server_port,
     ^
cc1: all warnings being treated as errors
make[5]: *** [ss_tunnel-tunnel.o] Error 1
make[5]: Leaving directory `/media/sos/OPENWRT/OpenWrt-SDK-15.05.1-ar71xx/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev/openssl/shadowsocks-libev/src'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory `/media/sos/OPENWRT/OpenWrt-SDK-15.05.1-ar71xx/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev/openssl/shadowsocks-libev'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/media/sos/OPENWRT/OpenWrt-SDK-15.05.1-ar71xx/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev/openssl/shadowsocks-libev'
make[2]: *** [/media/sos/OPENWRT/OpenWrt-SDK-15.05.1-ar71xx/build_dir/target-mips_34kc_uClibc-0.9.33.2/shadowsocks-libev/openssl/shadowsocks-libev/.built] Error 2
make[2]: Leaving directory `/media/sos/OPENWRT/OpenWrt-SDK-15.05.1-ar71xx/package/shadowsocks-libev'
make[1]: *** [package/shadowsocks-libev/compile] Error 2
make[1]: Leaving directory `/media/sos/OPENWRT/OpenWrt-SDK-15.05.1-ar71xx'
make: *** [package/shadowsocks-libev/compile] 错误 2

3月25号的代码编译都没问题
27号过后我看有其他的同学在上传新代码，但是无论如何再也编译不过去了
@breakwa11

**Comment by chobitsos** [comment]
@Noisyfox 
编译了f208f92f954128acd6c20064defba8920385e8ad
local.h第34行和local.c第69行之后openwrt无法编译过去

**Comment by chobitsos** [comment]
@Noisyfox
你别把那啥看不懂的分支合并进来啊，现在搞的我发现了炒鸡多的BUG，但是根本无从下手:put_litter_in_its_place::put_litter_in_its_place::put_litter_in_its_place:

**Comment by breakwa11** [comment]
dup #34

**Comment by 523860169** [comment]
你能不能分享下makefile，我改成https://github.com/shadowsocksr/shadowsocksr-libev/commit/2670ab26ddd63dd790ba6c35f57d4dd040dec194这个还是主楼的报错
