### ISSUE TITLE
今天下载的代码编译失败(linux 64)

### ISSUE THREAD

**Issue by meilihao** [shadowsocksr/shadowsocksr-libev#39]
make
make  all-recursive
make[1]: Entering directory '/home/chen/Documents/shadowsocksr-libev-master'
Making all in libsodium
make[2]: Entering directory '/home/chen/Documents/shadowsocksr-libev-master/libsodium'
Making all in src
make[3]: Entering directory '/home/chen/Documents/shadowsocksr-libev-master/libsodium/src'
Making all in libsodium
make[4]: Entering directory '/home/chen/Documents/shadowsocksr-libev-master/libsodium/src/libsodium'
Making all in include
make[5]: Entering directory '/home/chen/Documents/shadowsocksr-libev-master/libsodium/src/libsodium/include'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/chen/Documents/shadowsocksr-libev-master/libsodium/src/libsodium/include'
make[5]: Entering directory '/home/chen/Documents/shadowsocksr-libev-master/libsodium/src/libsodium'
make[5]: Nothing to be done for 'all-am'.
make[5]: Leaving directory '/home/chen/Documents/shadowsocksr-libev-master/libsodium/src/libsodium'
make[4]: Leaving directory '/home/chen/Documents/shadowsocksr-libev-master/libsodium/src/libsodium'
make[4]: Entering directory '/home/chen/Documents/shadowsocksr-libev-master/libsodium/src'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/home/chen/Documents/shadowsocksr-libev-master/libsodium/src'
make[3]: Leaving directory '/home/chen/Documents/shadowsocksr-libev-master/libsodium/src'
make[3]: Entering directory '/home/chen/Documents/shadowsocksr-libev-master/libsodium'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/chen/Documents/shadowsocksr-libev-master/libsodium'
make[2]: Leaving directory '/home/chen/Documents/shadowsocksr-libev-master/libsodium'
Making all in libcork
make[2]: Entering directory '/home/chen/Documents/shadowsocksr-libev-master/libcork'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/chen/Documents/shadowsocksr-libev-master/libcork'
Making all in libipset
make[2]: Entering directory '/home/chen/Documents/shadowsocksr-libev-master/libipset'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/chen/Documents/shadowsocksr-libev-master/libipset'
Making all in libudns
make[2]: Entering directory '/home/chen/Documents/shadowsocksr-libev-master/libudns'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/chen/Documents/shadowsocksr-libev-master/libudns'
Making all in libev
make[2]: Entering directory '/home/chen/Documents/shadowsocksr-libev-master/libev'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/chen/Documents/shadowsocksr-libev-master/libev'
Making all in src
make[2]: Entering directory '/home/chen/Documents/shadowsocksr-libev-master/src'
  CC       ss_tunnel-tunnel.o
tunnel.c: In function ‘server_recv_cb’:
tunnel.c:212:27: error: ‘cipher_env’ undeclared (first use in this function)
     int err = ss_encrypt(&cipher_env, remote->buf, server->e_ctx, BUF_SIZE);
                           ^~~~~~~~~~
tunnel.c:212:27: note: each undeclared identifier is reported only once for each function it appears in
tunnel.c: In function ‘remote_recv_cb’:
tunnel.c:394:27: error: ‘cipher_env’ undeclared (first use in this function)
     int err = ss_decrypt(&cipher_env, server->buf, server->d_ctx, BUF_SIZE);
                           ^~~~~~~~~~
tunnel.c: In function ‘remote_send_cb’:
tunnel.c:531:35: error: ‘cipher_env’ undeclared (first use in this function)
             int err = ss_encrypt(&cipher_env, remote->buf, server->e_ctx, BUF_SIZE);
                                   ^~~~~~~~~~
tunnel.c: In function ‘new_server’:
tunnel.c:680:23: error: ‘cipher_env’ undeclared (first use in this function)
         enc_ctx_init(&cipher_env, server->e_ctx, 1);
                       ^~~~~~~~~~
tunnel.c: In function ‘free_server’:
tunnel.c:701:30: error: ‘cipher_env’ undeclared (first use in this function)
             enc_ctx_release(&cipher_env, server->e_ctx);
                              ^~~~~~~~~~
tunnel.c: In function ‘main’:
tunnel.c:1005:30: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘remote_num’
             remote_num = conf->remote_num;
                              ^~
tunnel.c:1007:38: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘remote_addr’
                 remote_addr[i] = conf->remote_addr[i];
                                      ^~
tunnel.c:1010:31: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘remote_port’
             remote_port = conf->remote_port;
                               ^~
tunnel.c:1013:30: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘local_addr’
             local_addr = conf->local_addr;
                              ^~
tunnel.c:1016:30: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘local_port’
             local_port = conf->local_port;
                              ^~
tunnel.c:1019:28: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘password’
             password = conf->password;
                            ^~
tunnel.c:1023:28: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘protocol’
             protocol = conf->protocol;
                            ^~
tunnel.c:1027:34: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘protocol_param’
             protocol_param = conf->protocol_param;
                                  ^~
tunnel.c:1031:26: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘method’
             method = conf->method;
                          ^~
tunnel.c:1035:24: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘obfs’
             obfs = conf->obfs;
                        ^~
tunnel.c:1039:30: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘obfs_param’
             obfs_param = conf->obfs_param;
                              ^~
tunnel.c:1131:23: error: ‘cipher_env’ undeclared (first use in this function)
     int m = enc_init(&cipher_env, password, method);
                       ^~~~~~~~~~
tunnel.c:1191:68: error: passing argument 9 of ‘init_udprelay’ from incompatible pointer type [-Werror=incompatible-pointer-types]
                       tunnel_addr, mtu, listen_ctx.timeout, iface, protocol, protocol_param);
                                                                    ^~~~~~~~
In file included from tunnel.h:31:0,
                 from tunnel.c:60:
common.h:40:5: note: expected ‘cipher_env_t * {aka struct <anonymous> *}’ but argument is of type ‘char *’
 int init_udprelay(const char *server_host, const char *server_port,
     ^~~~~~~~~~~~~
tunnel.c:1189:9: error: too few arguments to function ‘init_udprelay’
         init_udprelay(local_addr, local_port, listen_ctx.remote_addr[0],
         ^~~~~~~~~~~~~
In file included from tunnel.h:31:0,
                 from tunnel.c:60:
common.h:40:5: note: declared here
 int init_udprelay(const char *server_host, const char *server_port,
     ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
Makefile:1561: recipe for target 'ss_tunnel-tunnel.o' failed
make[2]: *** [ss_tunnel-tunnel.o] Error 1
make[2]: Leaving directory '/home/chen/Documents/shadowsocksr-libev-master/src'
Makefile:469: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/chen/Documents/shadowsocksr-libev-master'
Makefile:377: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by breakwa11** [comment]
dup #34
