### ISSUE TITLE
ubuntu 16.04 LTS编译失败

### ISSUE THREAD

**Issue by gh0sting** [shadowsocksr/shadowsocksr-libev#41]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2017-04-21 master 分支

### What operating system are you using?
ubuntu 16.04 LTS

### What did you do?
./configure --disable-documentation
make

### What did you expect to see?
tunnel.c:1023:28: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘protocol’
             protocol = conf->protocol;
                            ^
tunnel.c:1027:34: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘protocol_param’
             protocol_param = conf->protocol_param;
                                  ^
tunnel.c:1031:26: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘method’
             method = conf->method;
                          ^
tunnel.c:1035:24: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘obfs’
             obfs = conf->obfs;
                        ^
tunnel.c:1039:30: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘obfs_param’
             obfs_param = conf->obfs_param;
                              ^
tunnel.c:1131:23: error: ‘cipher_env’ undeclared (first use in this function)
     int m = enc_init(&cipher_env, password, method);
                       ^
tunnel.c:1191:68: error: passing argument 9 of ‘init_udprelay’ from incompatible pointer type [-Werror=incompatible-pointer-types]
                       tunnel_addr, mtu, listen_ctx.timeout, iface, protocol, protocol_param);
                                                                    ^
In file included from tunnel.h:31:0,
                 from tunnel.c:60:
common.h:40:5: note: expected ‘cipher_env_t * {aka struct <anonymous> *}’ but argument is of type ‘char *’
 int init_udprelay(const char *server_host, const char *server_port,
     ^
tunnel.c:1189:9: error: too few arguments to function ‘init_udprelay’
         init_udprelay(local_addr, local_port, listen_ctx.remote_addr[0],
         ^
In file included from tunnel.h:31:0,
                 from tunnel.c:60:
common.h:40:5: note: declared here
 int init_udprelay(const char *server_host, const char *server_port,
     ^
cc1: all warnings being treated as errors
Makefile:1561: recipe for target 'ss_tunnel-tunnel.o' failed
make[2]: *** [ss_tunnel-tunnel.o] Error 1
make[2]: Leaving directory '/home/sean/dev_app/shadowsocksr-libev/src'
Makefile:469: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/sean/dev_app/shadowsocksr-libev'
Makefile:377: recipe for target 'all' failed
make: *** [all] Error 2
exit 2

### What did you see instead?
no

### What is your config in detail (with all sensitive info masked)?
no change

**Comment by breakwa11** [comment]
dup #34
