### ISSUE TITLE
不支持混淆？

### ISSUE THREAD

**Issue by makingworld** [shadowsocksr/shadowsocksr-libev#42]
按照rss推荐的配置，总是handshake failed
看了下issue，有的回答增加了混淆加密选项，有的又回答只是客户端，没有改动过，也没找到任何说明
所以这个libev到底支不支持混淆？还是和原版一样？

**Comment by breakwa11** [comment]
@makingworld 这个是客户端

**Comment by makingworld** [comment]
@breakwa11 python的是服务端？

**Comment by breakwa11** [comment]
@makingworld python是唯一的一个服务端，同时也是客户端

**Comment by makingworld** [comment]
@breakwa11 大概懂了，么么哒
