### ISSUE TITLE
最新代码编译报错

### ISSUE THREAD

**Issue by ekenchan** [shadowsocksr/shadowsocksr-libev#43]
tunnel.c: In function ‘server_recv_cb’:
tunnel.c:212:27: error: ‘cipher_env’ undeclared (first use in this function)
     int err = ss_encrypt(&cipher_env, remote->buf, server->e_ctx, BUF_SIZE);
                           ^
tunnel.c:212:27: note: each undeclared identifier is reported only once for each function it appears in
tunnel.c: In function ‘remote_recv_cb’:
tunnel.c:394:27: error: ‘cipher_env’ undeclared (first use in this function)
     int err = ss_decrypt(&cipher_env, server->buf, server->d_ctx, BUF_SIZE);
                           ^
tunnel.c: In function ‘remote_send_cb’:
tunnel.c:531:35: error: ‘cipher_env’ undeclared (first use in this function)
             int err = ss_encrypt(&cipher_env, remote->buf, server->e_ctx, BUF_SIZE);
                                   ^
tunnel.c: In function ‘new_server’:
tunnel.c:680:23: error: ‘cipher_env’ undeclared (first use in this function)
         enc_ctx_init(&cipher_env, server->e_ctx, 1);
                       ^
tunnel.c: In function ‘free_server’:
tunnel.c:701:30: error: ‘cipher_env’ undeclared (first use in this function)
             enc_ctx_release(&cipher_env, server->e_ctx);
                              ^
tunnel.c: In function ‘main’:
tunnel.c:1005:30: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘remote_num’
             remote_num = conf->remote_num;
                              ^
tunnel.c:1007:38: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘remote_addr’
                 remote_addr[i] = conf->remote_addr[i];
                                      ^
tunnel.c:1010:31: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘remote_port’
             remote_port = conf->remote_port;
                               ^
tunnel.c:1013:30: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘local_addr’
             local_addr = conf->local_addr;
                              ^
tunnel.c:1016:30: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘local_port’
             local_port = conf->local_port;
                              ^
tunnel.c:1019:28: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘password’
             password = conf->password;
                            ^
tunnel.c:1023:28: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘protocol’
             protocol = conf->protocol;
                            ^
tunnel.c:1027:34: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘protocol_param’
             protocol_param = conf->protocol_param;
                                  ^
tunnel.c:1031:26: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘method’
             method = conf->method;
                          ^
tunnel.c:1035:24: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘obfs’
             obfs = conf->obfs;
                        ^
tunnel.c:1039:30: error: ‘jconf_t {aka struct <anonymous>}’ has no member named ‘obfs_param’
             obfs_param = conf->obfs_param;
                              ^
tunnel.c:1131:23: error: ‘cipher_env’ undeclared (first use in this function)
     int m = enc_init(&cipher_env, password, method);
                       ^
tunnel.c:1191:68: error: passing argument 9 of ‘init_udprelay’ from incompatible pointer type [-Werror=incompatible-pointer-types]
                       tunnel_addr, mtu, listen_ctx.timeout, iface, protocol, protocol_param);
                                                                    ^
In file included from tunnel.h:31:0,
                 from tunnel.c:60:
common.h:40:5: note: expected ‘cipher_env_t * {aka struct <anonymous> *}’ but argument is of type ‘char *’
 int init_udprelay(const char *server_host, const char *server_port,
     ^
tunnel.c:1189:9: error: too few arguments to function ‘init_udprelay’
         init_udprelay(local_addr, local_port, listen_ctx.remote_addr[0],

**Comment by breakwa11** [comment]
#34
