### ISSUE TITLE
怎么安装和配置shadowsocksr-libev？这个版本是否没有扩展成shadowsocksr？

### ISSUE THREAD

**Issue by asymt** [shadowsocksr/shadowsocksr-libev#48]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
I using shadowsocks-libev version 2.5.6

### What operating system are you using?
my operating system is ubuntu 14.04 

### What did you do?
apt-get install shadowsocks-libev

### What did you expect to see?
how can I use shadowsocksr-libev

### What did you see instead?
nothing

### What is your config in detail (with all sensitive info masked)?
1 core 512mem

**Comment by breakwa11** [comment]
你是不是要先读一下WIKI

**Comment by asymt** [comment]
难道我在我的ubuntu上直接使用sudo apt-get install shadowsocks-libev安装就可以了，只要我使用shadowsocksr的客户端就能直接连？

**Comment by breakwa11** [comment]
如果你还是不去看WIKI，那我就不理你了

**Comment by qinyuhang** [comment]
你这句话 似乎有点表意不明。

**Comment by asymt** [comment]
OK！我找来找去还是没找到你说的可以解决我问题的Wiki页面在哪里，能直接告诉我浏览哪个页面可以解决我的问题吗？

**Comment by asymt** [comment]
@qinyuhang 其实我的意思很简单，就是我在我的ubuntu系统上已经用apt-get install shadowsocks-libev安装过了shadowsocks-libev，我要怎么设置才能使用shadowsocksr的协议和混淆功能？

**Comment by breakwa11** [comment]
@asymt 重装

**Comment by asymt** [comment]
按你这个项目下面的README文档重装？

**Comment by asymt** [comment]
还是装shadowsocks-libev版吗？
