### ISSUE TITLE
auth_chain_a not supported?

### ISSUE THREAD

**Issue by bash99** [shadowsocksr/shadowsocksr-libev#49]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
commit 2e4b8ef9a56c80714bd0c6e725eb524eea1e8fdc
Author: 破娃酱 <mmgac001@gmail.com>
Date:   Sun May 7 22:16:56 2017 +0800

### What operating system are you using?
debian 8

### What did you do?
try connected to server with auth_chain_a OBFS
./ss-local -s xxx.xxx.xxx -p 443 -k xxx -m none -O auth_chain_a -o tls1.2_ticket_auth -l 40774

### What did you expect to see?
normal connected

### What did you see instead?
 2017-05-09 11:07:55 INFO: initializing ciphers... none
 2017-05-09 11:07:55 ERROR: Load obfs 'auth_chain_a' failed

### What is your config in detail (with all sensitive info masked)?
{
    "server": "0.0.0.0",
    "server_ipv6": "::",
    "server_port": 443,
    "local_address": "127.0.0.1",
    "local_port": 1081,
    "password": "xxx.xxx.xxx",
    "timeout": 120,
    "udp_timeout": 60,
    "method": "none",
    "protocol": "auth_chain_a",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",
    "dns_ipv6": false,
    "connect_verbose_info": 1,
    "redirect": "*:8443#xxx.xxx.xxx:18443",
    "fast_open": false,
    "workers": 1

}

**Comment by safeoy** [comment]
m

**Comment by breakwa11** [comment]
why you don't see the commit history
