### ISSUE TITLE
ss-tunnel and ss-server will be deprecate?

### ISSUE THREAD

**Issue by angusding** [shadowsocksr/shadowsocksr-libev#51]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.5.6-20170325

### What operating system are you using?
OpenWrt

### What did you do?
Update to the latest version.

### What did you expect to see?
ss-tunnel and ss-server is OK.

### What did you see instead?
No ss-tunnel and ss-server in the latest version.

### What is your config in detail (with all sensitive info masked)?
Compile  with the original configurations.

**Comment by kdaye** [comment]
同问,
我git了最新的shadowsocksr-libev并且编译了..只有ss-local和ss-redir
不知道该如何让我之前配置的dnsmasq+ipset运行
dnsmasq+ipset configure
```
server=/.google.com/127.0.0.1#5353
ipset=/.google.com/gfwlist
```

**Comment by breakwa11** [comment]
yes, ss-tunnel and ss-server will be deprecate
ss-local can do anything what ss-tunnel can do

**Comment by angusding** [comment]
I think that ss-tunnel is a optional scheme for secure DNS in OpenWrt/LEDE Router and ss-server also is a  feasible server without python in Router.
Would you please recover them for Linux router?

**Comment by breakwa11** [comment]
@angusding no, ss-tunnel has been merged into ss-local

**Comment by lucifer9** [comment]
So what about ss-server ? Which one can I use to replace it ? And how ?
Thanks.
