### ISSUE TITLE
ssr-server 

### ISSUE THREAD

**Issue by odkrys** [shadowsocksr/shadowsocksr-libev#59]
Is there any specific reason to deprecate ssr-server ?
I need it to set up on my server on asus router.
I can't completely move from SS-libev to SSR-libev because of server feature.

Could you restore it again ?

**Comment by breakwa11** [comment]
@odkrys This is NOT SSR server

**Comment by odkrys** [comment]
@breakwa11 what's mean? 
Now I am running local and redir with my SSR vps successfully.
I changed the name of them to distinguish SSR from SS while build ss-local > ssr-local ss-redir > ssr-redir.

More exactly, ss-server.

**Comment by breakwa11** [comment]
I say it again: that is ss-server, NOT ssr-server
If you want a ssr-server, please write the fxxking code
ONLY Python branch has the server of SSR
